version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  target-branch: develop
  ignore:
  - dependency-name: pylint
    versions:
    - 2.6.0
    - 2.6.2
    - 2.7.0
    - 2.7.1
    - 2.7.2
    - 2.7.3
    - 2.7.4
    - 2.8.1
  - dependency-name: pre-commit
    versions:
    - 2.10.0
    - 2.10.1
    - 2.11.0
    - 2.11.1
    - 2.12.0
  - dependency-name: asgiref
    versions:
    - 3.3.1
    - 3.3.2
  - dependency-name: phonenumbers
    versions:
    - 8.12.17
    - 8.12.18
    - 8.12.19
    - 8.12.20
  - dependency-name: regex
    versions:
    - 2020.11.13
    - 2021.3.17
  - dependency-name: django
    versions:
    - 3.0.7
