# Generated by Django 3.0.5 on 2020-04-16 23:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="invoice", name="price",),
        migrations.AddField(
            model_name="invoice",
            name="date",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
