# Generated by Django 3.0.5 on 2020-04-17 01:20

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0002_auto_20200417_0238"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="date",
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 17, 4, 20, 11, 310521)),
        ),
    ]
