# Generated by Django 3.0.3 on 2020-05-01 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0008_invoice_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice", name="receipt", field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
