# Generated by Django 3.0.3 on 2020-05-03 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0012_invoice_status"),
    ]

    operations = [
        migrations.RenameField(model_name="invoice", old_name="rate", new_name="price",),
    ]
