# Generated by Django 3.0.2 on 2020-04-03 22:35

import django.db.models.deletion
import django_countries.fields
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Accommodation",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("RV", "RV"),
                            ("Travel Trailer", "Travel Trailer"),
                            ("Shiftpod", "Shiftpod"),
                            ("Kodiak Tent", "Kodiak Tent"),
                            ("No Bake Tent", "No Bake Tent"),
                            ("Siesta2 Tent", "Siesta2 Tent"),
                            ("Siesta4 Tent", "Siesta4 Tent"),
                            ("Small Tent (Under 10'x10')", "Small Tent (Under 10'x10')"),
                            ("Medium Tent (Fits in 10'x10')", "Medium Tent (Fits in 10'x10')"),
                            ("Large Tent (Larger than 10'x10')", "Large Tent (Larger than 10'x10')"),
                            ("Other", "Other"),
                        ],
                        max_length=127,
                    ),
                ),
                ("is_full", models.BooleanField(default=False)),
                ("name", models.CharField(max_length=127)),
            ],
        ),
        migrations.CreateModel(
            name="BubblyMember",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_leadership", models.BooleanField(default=False)),
                ("birthday", models.DateField()),
                (
                    "gender_identity",
                    models.CharField(
                        blank=True, default=None, help_text="To ensure camp diversity", max_length=127, null=True
                    ),
                ),
                (
                    "ethnic_identity",
                    models.CharField(
                        blank=True, default=None, help_text="To ensure camp diversity", max_length=127, null=True
                    ),
                ),
                ("country", django_countries.fields.CountryField(max_length=2)),
                ("city", models.CharField(max_length=127)),
                ("photo", models.ImageField(blank=True, default=None, null=True, upload_to="")),
                ("facebook", models.URLField(blank=True, default=None, max_length=1023, null=True)),
                ("phone_number", phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ("paypal_email", models.EmailField(max_length=254)),
                ("verified_email", models.BooleanField(default=False)),
                ("playa_name", models.CharField(blank=True, default=None, max_length=127, null=True)),
                (
                    "burning_man_profile_email",
                    models.EmailField(
                        help_text="Burning Man profile email address (MUST match https://profiles.burningman.org/ email)",
                        max_length=254,
                    ),
                ),
                ("is_virgin_burner", models.BooleanField(default=True)),
                (
                    "years_attending_burning_man",
                    models.CharField(
                        blank=True,
                        default=None,
                        help_text="Please separate them with commas",
                        max_length=127,
                        null=True,
                    ),
                ),
                ("allergies", models.TextField(blank=True, default=None, null=True)),
                ("medical_issues", models.TextField(blank=True, default=None, null=True)),
                (
                    "referring_member",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="MembershipApp.BubblyMember",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
                ),
            ],
            options={"abstract": False,},
        ),
        migrations.CreateModel(
            name="VehiclePass",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("secured", models.BooleanField(default=False, help_text="Please tick if you have a vehicle pass")),
                ("needed", models.BooleanField(default=False, help_text="Please tick if you need a vehicle pass")),
                ("ride_share", models.PositiveIntegerField(help_text="Number of extra room with you")),
                (
                    "number",
                    models.CharField(
                        blank=True,
                        default=None,
                        help_text="ID number found on the back of your ticket",
                        max_length=127,
                        null=True,
                    ),
                ),
                ("make", models.CharField(blank=True, default=None, max_length=127, null=True)),
                ("model", models.CharField(blank=True, default=None, max_length=127, null=True)),
                ("tow_hitch", models.BooleanField(default=False, help_text="Please tick if you have a tow hitch")),
                ("price", models.PositiveIntegerField(blank=True, default=None, null=True)),
                (
                    "holder",
                    models.ForeignKey(
                        help_text="Name of the current vehicle pass holder",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="MembershipApp.BubblyMember",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserAccommodationRelation",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "accommodation",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="MembershipApp.Accommodation"),
                ),
                (
                    "member",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="MembershipApp.BubblyMember"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Ticket",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("secured", models.BooleanField(default=False, help_text="Please tick if you have a ticket ")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pre Sale", "Pre Sale"),
                            ("Main Sale", "Main Sale"),
                            ("DGS", "DGS"),
                            ("OMG Sale", "OMG Sale"),
                            ("Low Income Approved", "Low Income Approved"),
                            ("STEP", "STEP"),
                            ("Third Party (Friend/Seller)", "Third Party (Friend/Seller)"),
                        ],
                        max_length=127,
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        blank=True,
                        default=None,
                        help_text="ID number found on the back of your ticket",
                        max_length=127,
                        null=True,
                    ),
                ),
                ("price", models.PositiveIntegerField(blank=True, default=None, null=True)),
                (
                    "holder",
                    models.ForeignKey(
                        help_text="Name of the current vehicle pass holder",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="MembershipApp.BubblyMember",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Burn",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "year",
                    models.IntegerField(
                        choices=[
                            (1984, 1984),
                            (1985, 1985),
                            (1986, 1986),
                            (1987, 1987),
                            (1988, 1988),
                            (1989, 1989),
                            (1990, 1990),
                            (1991, 1991),
                            (1992, 1992),
                            (1993, 1993),
                            (1994, 1994),
                            (1995, 1995),
                            (1996, 1996),
                            (1997, 1997),
                            (1998, 1998),
                            (1999, 1999),
                            (2000, 2000),
                            (2001, 2001),
                            (2002, 2002),
                            (2003, 2003),
                            (2004, 2004),
                            (2005, 2005),
                            (2006, 2006),
                            (2007, 2007),
                            (2008, 2008),
                            (2009, 2009),
                            (2010, 2010),
                            (2011, 2011),
                            (2012, 2012),
                            (2013, 2013),
                            (2014, 2014),
                            (2015, 2015),
                            (2016, 2016),
                            (2017, 2017),
                            (2018, 2018),
                            (2019, 2019),
                            (2020, 2020),
                        ]
                    ),
                ),
                ("arrival_time", models.DateTimeField(blank=True, default=None, null=True)),
                ("departure_time", models.DateTimeField(blank=True, default=None, null=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Burner Air", "Burner Air"),
                            ("Burner Bus", "Burner Bus"),
                            ("Carpool", "Carpool"),
                            (
                                "Own Transportation (will need vehicle pass)",
                                "Own Transportation (will need vehicle pass)",
                            ),
                            ("Other", "Other"),
                        ],
                        max_length=127,
                    ),
                ),
                (
                    "camp_dues",
                    models.PositiveIntegerField(
                        default=0, help_text="Payment that each camping member should pay to join bubbly camp"
                    ),
                ),
                ("camp_dues_paid", models.PositiveIntegerField(default=0)),
                (
                    "strike_deposit",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Payment that each camping member should pay to make sure they help cleaning before leaving",
                    ),
                ),
                ("strike_deposit_paid", models.PositiveIntegerField(default=0)),
                (
                    "meal_plan",
                    models.BooleanField(
                        default=False, help_text="Payment that each camping member should pay to join the meal plan"
                    ),
                ),
                ("meal_plan_paid", models.PositiveIntegerField(default=0)),
                ("notes", models.TextField(blank=True, default=None, null=True)),
                ("accommodations", models.ManyToManyField(to="MembershipApp.Accommodation")),
                (
                    "member",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="MembershipApp.BubblyMember"),
                ),
                (
                    "ticket",
                    models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="MembershipApp.Ticket"),
                ),
                (
                    "vehicle_pass",
                    models.OneToOneField(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="MembershipApp.VehiclePass",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="accommodation",
            name="members",
            field=models.ManyToManyField(
                through="MembershipApp.UserAccommodationRelation", to="MembershipApp.BubblyMember"
            ),
        ),
    ]
