# Generated by Django 3.0.2 on 2020-04-05 11:37

import django.core.validators
from django.db import migrations, models

import MembershipApp.models


class Migration(migrations.Migration):
    dependencies = [
        ("MembershipApp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="burn",
            name="year",
            field=models.PositiveIntegerField(
                validators=[django.core.validators.MinValueValidator(1984), MembershipApp.models.max_value_current_year]
            ),
        ),
    ]
