# Generated by Django 3.0.3 on 2020-04-16 00:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("MembershipApp", "0002_auto_20200416_0004"),
    ]

    operations = [
        migrations.RenameField(model_name="burn", old_name="type", new_name="transportation",),
    ]
