# Generated by Django 3.0.3 on 2020-05-04 00:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("MembershipApp", "0005_auto_20200427_1624"),
        ("MembershipApp", "0003_auto_20200416_0018"),
    ]

    operations = []
