# Generated by Django 3.0.3 on 2020-05-04 00:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("MembershipApp", "0006_merge_20200504_0004"),
    ]

    operations = [
        migrations.RenameModel(old_name="bubblyevents", new_name="BubblyEvent", ),
    ]
