# Generated by Django 3.0.3 on 2020-05-05 12:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("MembershipApp", "0007_auto_20200504_0008"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="member",
            field=models.ForeignKey(
                help_text="Name of the current vehicle pass holder\n",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
