# Generated by Django 3.0.3 on 2020-05-06 00:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("MembershipApp", "0009_auto_20200505_1243"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accommodation",
            name="is_full",
            field=models.BooleanField(
                default=False, help_text="<small><i>Please tick if your vehicle is full</small></i><br>"
            ),
        ),
        migrations.AlterField(
            model_name="bubblymember",
            name="burning_man_profile_email",
            field=models.EmailField(
                help_text="<small><i>Burning Man profile email address (MUST match https://profiles.burningman.org/ email) </small></i><br>",
                max_length=254,
            ),
        ),
        migrations.AlterField(
            model_name="bubblymember",
            name="ethnic_identity",
            field=models.CharField(
                blank=True,
                default=None,
                help_text="<small><i>To ensure camp diversity </small></i><br>",
                max_length=127,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="bubblymember",
            name="gender_identity",
            field=models.CharField(
                blank=True,
                default=None,
                help_text="<small><i>To ensure camp diversity </small></i><br>",
                max_length=127,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="bubblymember",
            name="years_attending_burning_man",
            field=models.CharField(
                blank=True,
                default=None,
                help_text="<small><i>Please separate them with commas </small></i><br>",
                max_length=127,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="burn",
            name="camp_dues",
            field=models.PositiveIntegerField(
                default=0,
                help_text="<small><i>Payment that each camping member should pay to join bubbly camp </small></i><br>",
            ),
        ),
        migrations.AlterField(
            model_name="burn",
            name="meal_plan",
            field=models.BooleanField(
                default=False,
                help_text="<small><i>Payment that each camping member should pay to join the meal plan </small></i><br>",
            ),
        ),
        migrations.AlterField(
            model_name="burn",
            name="strike_deposit",
            field=models.PositiveIntegerField(
                default=0,
                help_text="<small><i>Payment that each camping member should pay to make sure they help cleaning before leaving </small></i><br>",
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="member",
            field=models.ForeignKey(
                help_text="<small><i>Name of the current vehicle pass holder </small></i><br>",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="number",
            field=models.CharField(
                blank=True,
                default=None,
                help_text="<small><i>ID number found on the back of your ticket </small></i><br>",
                max_length=127,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="secured",
            field=models.BooleanField(
                default=False, help_text="<small><i>Please tick if you have a ticket </small></i><br>"
            ),
        ),
        migrations.AlterField(
            model_name="vehiclepass",
            name="member",
            field=models.ForeignKey(
                help_text="<small><i>Name of the current vehicle pass holder</small></i><br>",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="vehiclepass",
            name="needed",
            field=models.BooleanField(
                default=False, help_text="<small><i>Please tick if you need a vehicle pass </small></i><br>"
            ),
        ),
        migrations.AlterField(
            model_name="vehiclepass",
            name="number",
            field=models.CharField(
                blank=True,
                default=None,
                help_text="<small><i>ID number found on the back of your ticket </small></i><br>",
                max_length=127,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="vehiclepass",
            name="ride_share",
            field=models.PositiveIntegerField(help_text="<small><i>Number of extra room with you </small></i><br>"),
        ),
        migrations.AlterField(
            model_name="vehiclepass",
            name="secured",
            field=models.BooleanField(
                default=False, help_text="<small><i>Please tick if you have a vehicle pass </small></i><br>"
            ),
        ),
        migrations.AlterField(
            model_name="vehiclepass",
            name="tow_hitch",
            field=models.BooleanField(
                default=False, help_text="<small><i>Please tick if you have a tow hitch </small></i><br>"
            ),
        ),
    ]
