# Generated by Django 3.0.3 on 2020-04-12 12:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=127)),
                ('description', models.TextField()),
                ('width', models.PositiveIntegerField(blank=True, help_text='in meters', null=True)),
                ('height', models.PositiveIntegerField(blank=True, help_text='in meters', null=True)),
                ('length', models.PositiveIntegerField(blank=True, help_text='in meters', null=True)),
                ('voltage', models.PositiveIntegerField(blank=True, help_text='If it is an electrical item', null=True)),
                ('wattage', models.PositiveIntegerField(blank=True, help_text='If it is an electrical item', null=True)),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.PositiveIntegerField()),
                ('picture', models.FileField(blank=True, null=True, upload_to='')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127)),
                ('items', models.ManyToManyField(blank=True, to='inventory.Item')),
            ],
        ),
    ]
