# Generated by Django 3.0.3 on 2020-04-25 17:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="category", name="items_type",),
    ]
