# Generated by Django 3.0.3 on 2020-04-16 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="items_type",
            field=models.CharField(
                choices=[("non_electrical_items", "Non Electrical Items"), ("electrical_items", "Electrical Items")],
                default="non_electrical_items",
                max_length=50,
            ),
        ),
    ]
