# Generated by Django 3.0.3 on 2020-05-05 12:26

from decimal import Decimal

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0002_remove_category_items_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="electricalitem",
            name="voltage",
            field=models.DecimalField(
                decimal_places=3,
                help_text="in Volts",
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(Decimal("0.001"))],
            ),
        ),
        migrations.AlterField(
            model_name="electricalitem",
            name="wattage",
            field=models.DecimalField(
                decimal_places=3,
                help_text="in Watts",
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(Decimal("0.001"))],
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="height",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                help_text="in meters",
                max_digits=12,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.001"))],
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="length",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                help_text="in meters",
                max_digits=12,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.001"))],
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="unit_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                help_text="in $",
                max_digits=12,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.001"))],
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="width",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                help_text="in meters",
                max_digits=12,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.001"))],
            ),
        ),
    ]
