# Generated by Django 3.0.3 on 2020-04-16 13:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("inventory", "0002_category_items_type"),
    ]

    operations = [
        migrations.RenameModel(old_name="ElectricItem", new_name="ElectricalItem",),
        migrations.RemoveField(model_name="category", name="items",),
        migrations.AddField(
            model_name="category",
            name="electrical_items",
            field=models.ManyToManyField(blank=True, to="inventory.ElectricalItem"),
        ),
    ]
