# Generated by Django 3.0.3 on 2020-04-16 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_auto_20200416_1621"),
    ]

    operations = [
        migrations.RemoveField(model_name="category", name="electrical_items",),
    ]
