# Generated by Django 3.0.3 on 2020-04-16 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0004_remove_category_electrical_items"),
    ]

    operations = [
        migrations.AddField(
            model_name="category", name="items", field=models.ManyToManyField(blank=True, to="inventory.Item"),
        ),
    ]
