# Generated by Django 3.0.3 on 2020-04-16 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0005_category_items"),
    ]

    operations = [
        migrations.AlterField(
            model_name="electricalitem", name="voltage", field=models.PositiveIntegerField(help_text="in Volts"),
        ),
        migrations.AlterField(
            model_name="electricalitem", name="wattage", field=models.PositiveIntegerField(help_text="in Watts"),
        ),
    ]
