# Generated by Django 3.0.3 on 2020-04-16 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0006_auto_20200416_1708"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="items",
            field=models.ManyToManyField(blank=True, to="inventory.ElectricalItem"),
        ),
    ]
