# Generated by Django 3.0.3 on 2020-04-18 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0011_auto_20200418_1400"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category", name="items", field=models.ManyToManyField(blank=True, to="inventory.Item"),
        ),
    ]
