# Generated by Django 3.0.3 on 2020-04-18 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0012_auto_20200418_1408"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item", name="unit_price", field=models.PositiveIntegerField(help_text="in $"),
        ),
    ]
